import { isNullOrUndefined } from 'util';
import { Position } from './enums/position.enum';

export class UserRolePermission
{

     public static GetRolPermissions(id: number) : string[]
    {
       var permissions = []
       var rp = this.rolePermissions.find((item: any) => item.roleId === id);
       if (!isNullOrUndefined(rp))
          permissions = rp.permissions;

       return permissions;
    
    }

    private static rolePermissions = [
      {
         roleId : Position.SystemAdmin, 
         permissions :[
        'procurement',
          'viewMRP',
             'newMrp',
             'editMrp',
             'deleteMrp',
             'saveMrp',
          'baseTable',
          'viewItem',
             'newItem',
             'editItem',
             'deleteItem',
             'saveItem',
          'viewVendor',
             'newVendor',
             'editVendor',
             'deleteVendor',
             'saveVendor',
          'viewMrpItem',
             'newMrpItem',
             'editMrpItem',
             'deleteMrpItem',
             'saveMrpItem',
          'viewMrpVendor',
             'newMrpVendor',
             'editMrpVendor',
             'deleteMrpVendor',
             'saveMrpVendor',  
          'viewMrpVendorFlow',
             'newMrpVendorFlow',
             'editMrpVendorFlow',
             'deleteMrpVendorFlow',
             'saveMrpVendorFlow',
             'replyMrpVendorFlow',
          'idcMrpVendorFlow',   
          'viewMrpDocument',
             'newMrpDocument',
             'editMrpDocument',
             'deleteMrpDocument',
             'saveMrpDocument',
          'viewTBE',
             'saveTBE',
          'viewCBE',
             'saveCBE',
          'viewContract',
             'newContract',
             'editContract',
             'deleteContract',
             'saveContract',
          'viewContractItem',
             'newContractItem',
             'editContractItem',
             'deleteContractItem',
             'saveContractItem',
          'viewContractGuaranty',
             'newContractGuaranty',
             'editContractGuaranty',
             'deleteContractGuaranty',
             'saveContractGuaranty',
         'viewContractTermPayment',
             'newContractTermPayment',
             'editContractTermPayment',
             'deleteContractTermPayment',
             'saveContractTermPayment',
         'viewVpis',
             'newVpis',
             'editVpis',
             'deleteVpis',
             'saveVpis',
          'viewVendorTransmittal', 
             'newVendorTransmittal',
             'editVendorTransmittal',
             'deleteVendorTransmittal',
             'saveVendorTransmittal',
          'viewVendorTransmittalDoc',         
             'newVendorTransmitalDoc',
             'editVendorTransmitalDoc',
             'saveVendorTransmittal',
             
       'engineering',    
          'viewDocumentApproval',
          'newDocumentApproval',
        'task',
            'createPlannedTask',
            'assignPlannedTask'  
                 
         ]
     },
     {
      roleId : Position.Expert, 
      permissions :[
       'procurement',
          /* 'viewMRP', */
          'viewMrpVendorFlow',
             'toPSLMrpVendorFlow',
              'idcMrpVendorFlow',
              'sendVendorFlowIdc',
              'viewVendorTransmittalDoc', 
           'engineering',    
              'viewDocumentApproval',
                 'newDocumentApproval',
                 'sendDocumentApproval',         
        'task',
            'toPSLApprovalTask',
            'createPlannedTask',
            'addPlannedTaskVersion',
        'baseInfo',    
            'viewProjectPosition', 
           ]
         },

        {
            roleId : Position.PSL, 
            permissions :[
             'procurement',
                'viewMRP',
                'viewItem',
                'baseTable',
                'viewVendor',
                'viewMrpItem',
                'viewMrpVendor',
                'viewMrpVendorFlow',
                  'editMrpVendorFlow',
                  'deleteMrpVendorFlow',
                  'replyMrpVendorFlow',
                  'toExpertMrpVendorFlow',
                  'toPMMrpVendorFlow',
                  'rejectByPSLMrpVendorFlow',
                'viewMrpDocument',
                'viewTBE',
                'idcMrpVendorFlow',
                'sendVendorFlowIdc',
                'replyVendorFlowIdc',
                'viewVendorTransmittalDoc',   
                'viewVpis',    
                'engineering',    
          'viewDocumentApproval',
                  'newDocumentApproval',
                  'sendDocumentApproval',
                  'pslApproveDocument',
                  'pslRejectDocument',             
          'task',
              'pslSubmitTask',
              'createPlannedTask',
              'addPlannedTaskVersion',
              'baseInfo',    
                  'viewProjectPosition', 
            ]
        },
        {
         roleId : Position.DesciplineHead, 
         permissions :[
          'procurement',
             'viewMRP',
             'viewItem',
             'baseTable',
             'viewVendor',
             'viewMrpItem',
             'viewMrpVendor',
             'viewMrpVendorFlow',
             'viewMrpDocument',
             'viewTBE',
             'idcMrpVendorFlow',
             'viewVendorTransmittalDoc',   
             'viewVpis',         
       'task',
        'baseInfo',    
            'viewProjectPosition', 
            'viewTimesheetChart'
         ]
     },
        {
            roleId : Position.ProjectManager, 
            permissions :[
             'procurement',
                'viewMRP',
                'baseTable',
                'viewItem',
                'viewVendor',
                'viewMrpItem',
                'viewMrpVendor',
                'viewMrpVendorFlow',
                   'approvedByPMMrpVendorFlow',
                   'rejectedByPMMrpVendorFlow',
                'idcMrpVendorFlow',
                'viewMrpDocument',
                'viewTBE',
                'viewCBE',
                'viewVendorTransmittalDoc',  
                'viewVpis', 
           'engineering',    
                'viewDocumentApproval',
                    'pmApproveDocument',
                    'pmRejectDocument',
           'task',  
              'assignPlannedTask',  
              'createPlannedTask',
              'addPlannedTaskVersion' ,
              'baseInfo',    
                  'viewProjectPosition', 
                  'viewTimesheetChart'
            ]
        },
        {
         roleId : Position.EngineeringManager, 
         permissions :[
          'procurement',
             'viewMRP',
             'baseTable',
             'viewItem',
             'viewVendor',
             'viewMrpItem',
             'viewMrpVendor',
             'viewMrpVendorFlow',
                'approvedByEMMrpVendorFlow',
                'rejectedByEMMrpVendorFlow',
             'idcMrpVendorFlow',
             'viewMrpDocument',
             'viewTBE',
             'viewCBE',
             'viewVendorTransmittalDoc',   
             'viewVpis',
         'engineering',    
             'viewDocumentApproval',
                 'emApproveDocument',
                 'emRejectDocument',
          'task',
              'createPlannedTask',
              'addPlannedTaskVersion',
              'baseInfo',    
                  'viewProjectPosition', 
                  'viewTimesheetChart' 
                       
         ]
     },
     {
      roleId : Position.Manager, 
      permissions :[
       'procurement',
          'viewMRP',
          'baseTable',
          'viewItem',
          'viewVendor',
          'viewMrpItem',
          'viewMrpVendor',
          'viewMrpVendorFlow',  
          'viewMrpDocument',
          'viewTBE',
          'viewCBE',
          'viewVendorTransmittalDoc',   
          'viewVpis',
      'engineering',    
          'viewDocumentApproval',
      'task',
      'baseInfo',    
            'viewProjectPosition',  
            'viewTimesheetChart'
                    
      ]
  },
     {
      roleId : Position.DataAnalyzer, 
      permissions :[
       'procurement',
          'viewMRP',
          'baseTable',
          'viewItem',
          'viewVendor',
          'viewMrpItem',
          'viewMrpVendor',
          'viewMrpVendorFlow',
          'idcMrpVendorFlow',
          'viewMrpDocument',
          'viewTBE',
          'viewCBE',
          'viewVendorTransmittalDoc',   
          'viewVpis',
       'task',
       'rejectedPlannedTasks',
       'viewTimesheetChart'
                    
      ]
      },

        {
         roleId : Position.ProcurementCoordinator, 
           permissions :[
          'procurement',
             'viewMRP',
                'newMrp',
                'editMrp',
                'deleteMrp',
                'saveMrp',
             'baseTable',
             'viewItem',
                'newItem',
                'editItem',
                'deleteItem',
                'saveItem',
             'viewVendor',
                'newVendor',
                'editVendor',
                'deleteVendor',
                'saveVendor',
             'viewMrpItem',
                'newMrpItem',
                'editMrpItem',
                'deleteMrpItem',
                'saveMrpItem',
           'viewMrpVendor',
                'newMrpVendor',
                'editMrpVendor',
                'deleteMrpVendor',
                'saveMrpVendor',    
             'viewMrpVendorFlow',
                'newMrpVendorFlow',
                'editMrpVendorFlow',
                'deleteMrpVendorFlow',
                'saveMrpVendorFlow',
                'postedToVendorMrpVendorFlow',
             'viewMrpDocument',
                'newMrpDocument',
                'editMrpDocument',
                'deleteMrpDocument',
                'saveMrpDocument',
             'viewTBE',
                'saveTBE',
             'viewCBE',
                'saveCBE',
                'viewContract',
                'newContract',
                'editContract',
                'deleteContract',
                'saveContract',
             'viewContractItem',
                'newContractItem',
                'editContractItem',
                'deleteContractItem',
                'saveContractItem',
             'viewContractGuaranty',
                'newContractGuaranty',
                'editContractGuaranty',
                'deleteContractGuaranty',
                'saveContractGuaranty',
            'viewContractTermPayment',
                'newContractTermPayment',
                'editContractTermPayment',
                'deleteContractTermPayment',
                'saveContractTermPayment',
            'viewVpis',
                'newVpis',
                'editVpis',
                'deleteVpis',
                'saveVpis',
           'viewVendorTransmittal', 
                'newVendorTransmittal',
                'editVendorTransmittal',
                'deleteVendorTransmittal',
                'saveVendorTransmittal',
            'viewVendorTransmittalDoc',
               'newVendorTransmitalDoc',
               'editVendorTransmitalDoc',
               'saveVendorTransmittal'  
            ]
        },
        {
         roleId : Position.QA, 
           permissions :[
            'task',
            'document',       
            'engineering',    
            'viewDocumentApproval',
               'qaApproveDocument',
               'qaRejectDocument',
            'viewTransmittal', 
               'newTransmittal',
               'editTransmittal',
               'deleteTransmittal',
               'saveTransmittal',
               'rejectedPlannedTasks',
            'viewTransmittalDoc',
              'newTransmittalDoc',
              'editTransmittalDoc',
              'deleteTransmittalDoc',
              'saveTransmittalDoc' 
           ]
         },
         {
          roleId : Position.DCC, 
            permissions :[  
            'engineering',    
               'viewDocumentApproval',
                  'dccApproveDocument',
                  'dccRejectDocument',                 
            'task',
                   'createPlannedTask',
                   'addPlannedTaskComment',
                   'changeDocTitle',
                   'deleteTask',
                   'rejectedPlannedTasks',
            'document',       
                'viewTransmittal', 
                   'newTransmittal',
                   'editTransmittal',
                   'deleteTransmittal',
                   'saveTransmittal',
                'viewTransmittalDoc',
                  'newTransmittalDoc',
                  'editTransmittalDoc',
                  'deleteTransmittalDoc',
                  'saveTransmittalDoc'              
            ]
         },  
        {
            roleId : Position.ITAndSystems, 
              permissions :[  
               'baseInfo',    
                  'viewUsers',
                     'newUser',
                     'editUser',                     
                     'deleteUser',
                     'saveUser',
                  'viewProject',
                     'saveProject',
                  'viewProjectPosition',
                    'assignProjectPosition',
                  'viewOrganizationPosition',
                    'assignOrganizationPosition',
                  'viewPctLevels',
                    'newPctLevel',
                    'editPctLevel',
                    'deletePctLevel',
                    'savePctLevel',  
                  'document',       
                    'viewTransmittalDocPCT',
                  'viewCustomers',
                    'newCustomer',
                    'editCustomer',                     
                    'deleteCustomer',
                    'saveCustomer',  
                    'rejectedPlannedTasks',
                  'viewActivity',
                    'newActivity',
                    'editActivity',                     
                    'deleteActivity',
                    'saveActivity',  
                    'viewTimesheetChart',
                    'allTimesheetReport',
                    'projectTimesheetReport'   

              ]
      },
      {
         roleId : Position.QualitySystemsManager, 
           permissions :[
            'baseInfo',    
               'viewUsers',
                  'newUser',
                  'editUser',                     
                  'deleteUser',
                  'saveUser',
               'viewProject',
                  'saveProject',
               'viewProjectPosition',
                  'assignProjectPosition',
               'viewOrganizationPosition',
                  'assignOrganizationPosition',
               'viewPctLevels',
                  'newPctLevel',
                  'editPctLevel',
                  'deletePctLevel',
                  'savePctLevel',  
                'viewCustomers',
                  'newCustomer',
                  'editCustomer',                     
                  'deleteCustomer',
                  'saveCustomer',  
               'viewActivity',
                  'newActivity',
                  'editActivity',                     
                  'deleteActivity',
                  'saveActivity',  

              'document',     
                  'viewTransmittalDocPCT',

                  'viewTimesheetChart',

                  'allTimesheetReport',
              'projectTimesheetReport'   

           ]
      },
      {
         roleId : Position.orgDCC, 
           permissions :[
            'baseInfo', 
            'viewUsers',
            'newUser',
            'editUser',                     
            'deleteUser',
            'saveUser',
         'viewProject',
            'saveProject',
         'viewProjectPosition',
           'assignProjectPosition',
         'viewOrganizationPosition',
           'assignOrganizationPosition',                
              
               'viewPctLevels',
               'newPctLevels',
               'editPctLevel',
               'deletePctLevel',
               'savePctLevel',  
               'document',      
               'viewTransmittalDocPCT',
               'viewCustomers',
                 'newCustomer',
                 'editCustomer',                     
                 'deleteCustomer',
                 'saveCustomer',  

                 'allTimesheetReport',
              'projectTimesheetReport'   

           ]
      },
      {
         roleId : Position.QAQC, 
           permissions :[
            'baseInfo',                   
            'viewUsers',
            'newUser',
            'editUser',                     
            'deleteUser',
            'saveUser',
         'viewProject',
            'saveProject',
         'viewProjectPosition',
           'assignProjectPosition',
         'viewOrganizationPosition',
           'assignOrganizationPosition',
               'viewPctLevels',
                 'newPctLevel',
                 'editPctLevel',
                 'deletePctLevel',
                 'savePctLevel',
               'document',       
                 'viewTransmittalDocPCT',
               'viewCustomers',
                  'newCustomer',
                  'editCustomer',                     
                  'deleteCustomer',
                  'saveCustomer', 
                  
                  'allTimesheetReport',
                 'projectTimesheetReport'   
           ]
      }
    ]
}